TARGET := MAX30102
C_DEFS := \

#-D DEBUG=0

#LIBS := -lCH57xRF

#NEEDS_UNBRICK = defined

#LIBDIR += -L"$(SELF_DIR)CH572libs/BLELIB"

#C_INCLUDES := -I"../../CH572libs/BLELIB" 

include ../../ch572.mk
