# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CC=/usr/bin/gcc
AS=/usr/bin/gcc
CXX=/usr/bin/gcc
MM=/usr/bin/gcc
MXX=/usr/bin/gcc

LD=/usr/bin/g++
SH=/usr/bin/g++
AR=/usr/bin/ar

AHTBLE_LD=/mnt/c/MRStoolChain/RISC-V Embedded GCC12/bin/riscv-wch-elf-gcc
AHTBLE_CC=/mnt/c/MRStoolChain/RISC-V Embedded GCC12/bin/riscv-wch-elf-gcc
BLELED_LD=/mnt/c/MRStoolChain/RISC-V Embedded GCC12/bin/riscv-wch-elf-gcc
BLELED_CC=/mnt/c/MRStoolChain/RISC-V Embedded GCC12/bin/riscv-wch-elf-gcc
ICM_LD=/mnt/c/MRStoolChain/RISC-V Embedded GCC12/bin/riscv-wch-elf-gcc
ICM_CC=/mnt/c/MRStoolChain/RISC-V Embedded GCC12/bin/riscv-wch-elf-gcc
ws2812_LD=/mnt/c/MRStoolChain/RISC-V Embedded GCC12/bin/riscv-wch-elf-gcc
ws2812_CC=/mnt/c/MRStoolChain/RISC-V Embedded GCC12/bin/riscv-wch-elf-gcc
